using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RepeatBackground : MonoBehaviour
{

    BoxCollider2D groundCollider;
    float groundLength;

    // Start is called before the first frame update
    void Start()
    {
        groundCollider = GetComponent<BoxCollider2D>();
        groundLength = groundCollider.size.x;
    }

    // Update is called once per frame
    void Update()
    {
        if (transform.position.x < -groundLength)
            ResetBackground();
    }

    void ResetBackground()
    {
        Vector2 groundOffset = new Vector2(groundLength * 2, 0);
        transform.position = (Vector2)transform.position + groundOffset;
    }

}
